[book]
authors = []
language = "en"
src = "src"
title = "English Learning Town"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
